# Only test master and pull requests; skip tags.
# Other branches can allow themselves.
branches:
  only:
    - master

# Prefer docker container with setuid/sudo
sudo: required

language: python

python:
  - "2.7"

cache: pip

services:
  - mysql
  - postgres

addons:
  apt:
    packages:
      - python-egenix-mxdatetime
      - python-mysqldb
      - python-psycopg2
      - python3-psycopg2
      - firebird2.5-super
  postgresql: "9.4"

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-mysqldb
    - python: "3.4"
      env: TOXENV=py34-mysqlclient
    - python: "3.5"
      env: TOXENV=py35-mysqlclient
    - python: "3.6"
      env: TOXENV=py36-mysqlclient
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37-mysqlclient
    - python: "2.7"
      env: TOXENV=py27-mysql-connector
    - python: "3.4"
      env: TOXENV=py34-mysql-connector
    - python: "3.5"
      env: TOXENV=py35-mysql-connector
    - python: "3.6"
      env: TOXENV=py36-mysql-connector
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37-mysql-connector
    - python: "2.7"
      env: TOXENV=py27-mysql-oursql
    - python: "3.4"
      env: TOXENV=py34-mysql-oursql3
    - python: "3.5"
      env: TOXENV=py35-mysql-oursql3
    - python: "3.6"
      env: TOXENV=py36-mysql-oursql3
    - python: "2.7"
      env: TOXENV=py27-pymysql
    - python: "3.4"
      env: TOXENV=py34-pymysql
    - python: "3.5"
      env: TOXENV=py35-pymysql
    - python: "3.6"
      env: TOXENV=py36-pymysql
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37-pymysql
    - python: "2.7"
      env: TOXENV=py27-postgres-psycopg
    - python: "3.4"
      env: TOXENV=py34-postgres-psycopg
    - python: "3.5"
      env: TOXENV=py35-postgres-psycopg
    - python: "3.6"
      env: TOXENV=py36-postgres-psycopg
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37-postgres-psycopg
    - python: "2.7"
      env: TOXENV=py27-postgres-pygresql
    - python: "3.4"
      env: TOXENV=py34-postgres-pygresql
    - python: "3.5"
      env: TOXENV=py35-postgres-pygresql
    - python: "3.6"
      env: TOXENV=py36-postgres-pygresql
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37-postgres-pygresql
    - python: "3.4"
      env: TOXENV=py34-pypostgresql
    - python: "3.5"
      env: TOXENV=py35-pypostgresql
    - python: "3.6"
      env: TOXENV=py36-pypostgresql
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37-pypostgresql
    - python: "2.7"
      env: TOXENV=py27-postgres-pg8000
    - python: "3.4"
      env: TOXENV=py34-postgres-pg8000
    - python: "3.5"
      env: TOXENV=py35-postgres-pg8000
    - python: "3.6"
      env: TOXENV=py36-postgres-pg8000
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37-postgres-pg8000
    - python: "2.7"
      env: TOXENV=py27-sqlite
    - python: "3.4"
      env: TOXENV=py34-sqlite
    - python: "3.5"
      env: TOXENV=py35-sqlite
    - python: "3.6"
      env: TOXENV=py36-sqlite
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37-sqlite
    - python: "2.7"
      env: TOXENV=py27-sqlite-memory
    - python: "3.4"
      env: TOXENV=py34-sqlite-memory
    - python: "3.5"
      env: TOXENV=py35-sqlite-memory
    - python: "3.6"
      env: TOXENV=py36-sqlite-memory
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37-sqlite-memory
    - python: "2.7"
      env: TOXENV=py27-flake8
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37-flake8
    - python: "2.7"
      env: TOXENV=py27-firebird-fdb
    - python: "3.6"
      env: TOXENV=py36-firebird-fdb
    - python: "2.7"
      env: TOXENV=py27-firebirdsql
    - python: "3.6"
      env: TOXENV=py36-firebirdsql

  allow_failures:
    - env: TOXENV=py27-firebird-fdb
    - env: TOXENV=py36-firebird-fdb
    - env: TOXENV=py27-firebirdsql
    - env: TOXENV=py36-firebirdsql

  fast_finish: true

before_install:
  # Start the firebird database server.
  # We use firebird-super, so there's none of the inetd configuration
  # required by firebird-classic.
  # We also create a test user for the firebird test and
  # create a script that can be fed into isql-fb
  # to create the test database.
  # Copied password initializtion from
  # https://github.com/xdenser/node-firebird-libfbclient/blob/master/.travis.yml
  - if [[ $TOXENV = *firebird* ]]; then
      sudo sed -i /etc/default/firebird2.5 -e 's/=no/=yes/' &&
      sudo /etc/init.d/firebird2.5-super start && sleep 5 &&
      sudo /bin/bash -c '(export FB_VER="2.5"; export FB_FLAVOUR="super";source /usr/share/firebird2.5-common/functions.sh; writeNewPassword masterkey)' &&
      sudo gsec -user sysdba -pass masterkey -add test -pw test &&
      sudo /bin/bash -c "echo \"CREATE DATABASE 'localhost:/tmp/test.fdb';\" > /var/lib/firebird/create_test_db" &&
      sudo chmod 644 /var/lib/firebird/create_test_db;
    fi

install: travis_retry pip install --upgrade pip setuptools tox coveralls codecov ppu

script: tox

after_success:
    - cd sqlobject
    - coveralls
    - codecov

before_cache:
  - remove-old-files.py -o 180 ~/.cache/pip
