# Install SQLObject on windows and test against MS SQL server and postgres
# Heavily inspired by Oliver Grisel's appveyor-demo (https://github.com/ogrisel/python-appveyor-demo)
# and Michael Sverdlik's appveyor-utils (https://github.com/cloudify-cosmo/appveyor-utils)
version: '{branch}-{build}'

# Only test master and pull requests; skip tags.
# Other branches can allow themselves.
branches:
  only:
    - master
skip_branch_with_pr: false
skip_tags: true

cache:
  - '%LOCALAPPDATA%\pip\Cache'

# Match travis
clone_depth: 50

services:
  - mysql
  - postgresql

environment:
  MYSQL_PWD: "Password12!"
  PGUSER: "postgres"
  PGPASSWORD: "Password12!"

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\run_with_env.cmd"

  matrix:
    - TOXENV: "py27-mysql-connector-w32"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "2.7"
      PYTHON_HOME: "C:\\Python27"
      db: mysql
    - TOXENV: "py36-mysql-connector-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6"
      PYTHON_HOME: "C:\\Python36-x64"
      db: mysql
    - TOXENV: "py27-pymysql-w32"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "2.7"
      PYTHON_HOME: "C:\\Python27"
      db: mysql
    - TOXENV: "py36-pymysql-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6"
      PYTHON_HOME: "C:\\Python36-x64"
      db: mysql
    - TOXENV: "py27-mysql-pyodbc-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "2.7"
      PYTHON_HOME: "C:\\Python27-x64"
      db: mysql
    - TOXENV: "py36-mysql-pyodbc-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6"
      PYTHON_HOME: "C:\\Python36-x64"
      db: mysql
    - TOXENV: "py27-postgres-psycopg-w32"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "2.7"
      PYTHON_HOME: "C:\\Python27"
      db: postgresql
    - TOXENV: "py36-postgres-psycopg-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6"
      PYTHON_HOME: "C:\\Python36-x64"
      db: postgresql
    - TOXENV: "py27-postgres-pygresql-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "2.7"
      PYTHON_HOME: "C:\\Python27-x64"
      db: postgresql
    - TOXENV: "py36-postgres-pygresql-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6"
      PYTHON_HOME: "C:\\Python36-x64"
      db: postgresql
    - TOXENV: "py36-pypostgresql-w32"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "3.6"
      PYTHON_HOME: "C:\\Python36"
      db: postgresql
    - TOXENV: "py36-pypostgresql-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6"
      PYTHON_HOME: "C:\\Python36-x64"
      db: postgresql
    - TOXENV: "py27-postgres-pg8000-w32"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "2.7"
      PYTHON_HOME: "C:\\Python27"
      db: postgresql
    - TOXENV: "py36-postgres-pg8000-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6"
      PYTHON_HOME: "C:\\Python36-x64"
      db: postgresql
    - TOXENV: "py27-postgres-pyodbc-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "2.7"
      PYTHON_HOME: "C:\\Python27-x64"
      db: postgresql
    - TOXENV: "py36-postgres-pyodbc-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6"
      PYTHON_HOME: "C:\\Python36-x64"
      db: postgresql
    - TOXENV: "py27-sqlite-w32"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "2.7"
      PYTHON_HOME: "C:\\Python27"
    - TOXENV: "py36-sqlite-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6"
      PYTHON_HOME: "C:\\Python36-x64"
    - TOXENV: "py27-sqlite-memory-w32"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "2.7"
      PYTHON_HOME: "C:\\Python27"
    - TOXENV: "py36-sqlite-memory-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6"
      PYTHON_HOME: "C:\\Python36-x64"

install:
  # Ensure we use the right python version
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin;C:\\Program Files\\PostgreSQL\\9.5\\bin;%PATH%"
  - "SET TOXPYTHON=%PYTHON_HOME%\\python.exe"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip --version"
  - "pip install --upgrade pip setuptools tox ppu"
  # List ODBC drivers
  - ps: Get-OdbcDriver -Platform 32-bit | Select-Object -ExpandProperty Name
  - ps: Get-OdbcDriver -Platform 64-bit | Select-Object -ExpandProperty Name

# Not a C project, so no build step
build: false

test_script:
  - "%CMD_IN_ENV% tox"

after_test:
  - "remove-old-files.py -o 180 %LOCALAPPDATA%\\pip\\Cache"
